@echo off
echo Starting FastAPI Backend...
cd backend
echo Installing dependencies...
pip install fastapi uvicorn python-multipart
echo Starting server on http://localhost:8000...
echo Using simplified backend for immediate functionality...
python -m uvicorn simple_main:app --reload --host 0.0.0.0 --port 8000
pause
